# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x06\x65ngine\",\n\x0e\x41nalyzeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\"M\n\x0f\x41nalyzeResponse\x12\x1e\n\x06status\x18\x01 \x01(\x0e\x32\x0e.engine.Status\x12\x0e\n\x06report\x18\x02 \x01(\t\x12\n\n\x02ir\x18\x03 \x01(\t*\x19\n\x06Status\x12\x06\n\x02Ok\x10\x00\x12\x07\n\x03\x45rr\x10\x01\x32H\n\x08\x41nalyzer\x12<\n\tDoAnalyze\x12\x16.engine.AnalyzeRequest\x1a\x17.engine.AnalyzeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=148
  _globals['_STATUS']._serialized_end=173
  _globals['_ANALYZEREQUEST']._serialized_start=23
  _globals['_ANALYZEREQUEST']._serialized_end=67
  _globals['_ANALYZERESPONSE']._serialized_start=69
  _globals['_ANALYZERESPONSE']._serialized_end=146
  _globals['_ANALYZER']._serialized_start=175
  _globals['_ANALYZER']._serialized_end=247
# @@protoc_insertion_point(module_scope)
